typography_spectrum: 0.8655914
color:
  saturation: 0.5
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#ffffff'
    - '#b1ffbe'
    - '#fbd4b2'
    - '#a1823b'
    - '#c8b56a'
  rhythmicContrast: 0.4982079
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/33e53d02-963e-445a-a036-c338b0e217ec.png
name: sayyesinaustria
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Say YES in Austria
purpose: []
