name: sayyesinaustria
favicon: null
layout_spectrum: 0
typography_spectrum: 0.886
title: Say YES in Austria
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b1ffbe'
    - '#fbd4b2'
    - '#a1823b'
    - '#c8b56a'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
